pluginManagement {
    repositories {
        maven("https://dl.bintray.com/kotlin/kotlin-eap")
        mavenCentral()
        maven("https://plugins.gradle.org/m2/")
    }
}
/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "JDABot"
